# windows-agent.conf
# <localfile> blocks from the windows agent on win-adevjiani located at "C:\Program Files (x86)\ossec-agent\ossec.conf"
# These blocks are to be added in addition to the default ossec.conf

#  Note the first block may already be there, but might not have event blocking by ID, it is unimportant for this scenario so leave as is if it already exists.
# The 2nd block is there to tell the wazuh agent to pass the sysmon event log channel to the manager
# The 3rd block is there to tell the wazuh agent to pass the powershell event log channel to the manager
# both require some configuration on the windows side of things for proper/any functionality

<ossec_config>
  <localfile>
    <location>Security</location>
    <log_format>eventchannel</log_format>
    <query>Event/System[EventID != 5145 and EventID != 5156 and EventID != 5447 and
      EventID != 4656 and EventID != 4658 and EventID != 4663 and EventID != 4660 and
      EventID != 4670 and EventID != 4690 and EventID != 4703 and EventID != 4907 and
      EventID != 5152 and EventID != 5157]</query>
  </localfile>

  <localfile>
    <location>Microsoft-Windows-Sysmon/Operational</location>
    <log_format>eventchannel</log_format>
  </localfile>

  <localfile>
    <location>Microsoft-Windows-PowerShell/Operational</location>
    <log_format>eventchannel</log_format>
  </localfile>
</ossec_config>